; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Jul 15 2022 22:50:33 GMT+0200 (Central European Summer Time)

M84